# Generated by Django 5.0.2 on 2024-02-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customer_supplier_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company'), ('Government', 'Government')], max_length=20, null=True),
        ),
    ]
