# Generated by Django 5.0.2 on 2024-02-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
