# Generated by Django 5.0.2 on 2024-02-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
    ]
