# Generated by Django 5.0.2 on 2024-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dicount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
