# Generated by Django 5.0.2 on 2024-02-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_order_dicount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dicount',
            new_name='discount',
        ),
    ]
