# Generated by Django 5.0.2 on 2024-02-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no-avatar.png', upload_to='Profile_Images'),
        ),
    ]
